apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base
  - ../../../reloader
  - ingress.yaml

images:
  - name: quay.io/argoproj/argocd
    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/quay/argoproj/argocd

  - name: public.ecr.aws/docker/library/redis
    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/docker/library/redis

  - name: public.ecr.aws/docker/library/haproxy
    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/docker/library/haproxy

  - name: ghcr.io/dexidp/dex
    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/github/dexidp/dex

patches:
 - path: patches.yaml
