apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - namespace.yml

helmCharts:
- name: vault
  namespace: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.31.0
  valuesFile: values.yml
  releaseName: edgeforge

labels:
- includeSelectors: true
  pairs:
    app: vault-app