apiVersion: v1
appVersion: 1.1.1
description: A Helm chart for the ACK service controller for Amazon Simple Storage
  Service (S3)
home: https://github.com/aws-controllers-k8s/s3-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
keywords:
- aws
- kubernetes
- s3
maintainers:
- name: ACK Admins
  url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
- name: S3 Admins
  url: https://github.com/orgs/aws-controllers-k8s/teams/s3-maintainer
name: s3-chart
sources:
- https://github.com/aws-controllers-k8s/s3-controller
version: 1.1.1
