apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kargo

resources:
  - namespace.yaml

images:
  - name: ghcr.io/akuity/kargo
    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/github/akuity/kargo

helmCharts:
- name: kargo
  repo: oci://ghcr.io/akuity/kargo-charts
  version: 1.8.3
  namespace: kargo
  valuesFile: values.yaml