name: Kustomize Build Check - Basic

on:
  pull_request:
    paths:
      - 'manifests/*'
    branches:
      - main

jobs:
  validate:
    name: Validate Kustomize Builds
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Required for git diff & gitversion
      
      - name: Run Kustomize Build Check
        uses: michielvha/kustomize-build-check@main
        with:
          enable-helm: true
          fail-on-error: true
